version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: aim_postgres_dev
    restart: unless-stopped
    environment:
      POSTGRES_DB: primarie_digital
      POSTGRES_USER: primarie_user
      POSTGRES_PASSWORD: primarie_secure_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U primarie_user -d primarie_digital"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: aim_redis_dev
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: aim_network